# Generated by Django 3.0.7 on 2020-06-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Users'},
        ),
    ]
